[package]
name = "processor-x"
version = "0.1.0"
edition = "2024"

[dependencies]
# Workspace crates
common = { path = "../../common" }

# External dependencies
log = { workspace = true }
regex = { workspace = true }
async-trait = { workspace = true }
